//AUTH variables
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const SET_LOADING_TRUE = "SET_LOADING_TRUE";
export const SET_LOADING_FALSE = "SET_LOADING_FALSE";
export const LOGOUT = "LOGOUT";
export const SET_EDIT_TRUE = "SET_EDIT_TRUE";
export const SET_EDIT_FALSE = "SET_EDIT_FALSE";
export const USER_EDIT_SUCCESS = "USER_EDIT_SUCCESS";
export const USER_EDIT_FAILED = "USER_EDIT_FAILED";
export const USER_EDIT_PASSWORD_FAILED = "USER_EDIT_PASSWORD_FAILED";
export const USER_EDIT_PASSWORD_SUCCESS = "USER_EDIT_PASSWORD_SUCCESS";
//ALERT variables
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const SET_ALERT_LOADING_TRUE = "SET_ALERT_LOADING_TRUE";
export const SET_ALERT_LOADING_FALSE = "SET_ALERT_LOADING_FALSE";
//FEEDBACK variables
export const FEEDBACK_ADDED = "FEEDBACK_ADDED";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const ALL_FEEDBACKS_LOADED = "ALL_FEEDBACKS_LOADED";
export const SET_REVIEWED_SUCCESS = "SET_REVIEWED_SUCCESS";
export const DELETE_FEEDBACK_SUCCESS = "DELETE_FEEDBACK_SUCCESS";
//USER variables
export const SET_USER_LOADING_TRUE = "SET_USER_LOADING_TRUE";
export const GET_SELECTED_USER_SUCCESS = "GET_SELECTED_USER_SUCCESS";
export const GET_USER_ITEMS_SUCCESS = "GET_USER_ITEMS_SUCCESS";
export const GET_USER_ITEMS_FAILED = "GET_USER_ITEMS_FAILED";
export const SET_USER_ITEMS_LOADING = "SET_USER_ITEMS_LOADING";
///CATEGORIES variables
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";
//FURNITURE variables
export const FURNITURE_ADDED = "FURNITURE_ADDED";
export const CLEAR_FURNITURE_MESSAGE = "CLEAR_FURNITURE_MESSAGE";
export const GET_ALL_FURNITURES_SUCCESS = "GET_ALL_FURNITURES_SUCCESS";
export const DELETE_FURNITURE_SUCCESS = "DELETE_FURNITURE_SUCCESS";
export const DELETE_FURNITURE_FAILED = "DELETE_FURNITURE_FAILED";
export const FURNITURE_EDIT_SUCCESS = "FURNITURE_EDIT_SUCCESS";
export const FURNITURE_EDIT_FAILED = "FURNITURE_EDIT_FAILED";
export const USER_FURNITURES_REMOVE = "USER_FURNITURES_REMOVE";
export const USER_FURNITURES_ARCHIVE_TOGGLE = "USER_FURNITURES_ARCHIVE_TOGGLE";
export const FURNITURE_ARCHIVE_TOGGLE = "FURNITURE_ARCHIVE_TOGGLE";

//VEHICLE variables
export const VEHICLE_ADDED = "VEHICLE_ADDED";
export const CLEAR_VEHICLE_MESSAGE = "CLEAR_VEHICLE_MESSAGE";
export const GET_ALL_VEHICLES_SUCCESS = "GET_ALL_VEHICLES_SUCCESS";
export const DELETE_VEHICLE_SUCCESS = "DELETE_VEHICLE_SUCCESS";
export const DELETE_VEHICLE_FAILED = "DELETE_VEHICLE_FAILED";
export const VEHICLE_EDIT_SUCCESS = "VEHICLE_EDIT_SUCCESS";
export const VEHICLE_EDIT_FAILED = "VEHICLE_EDIT_FAILED";
export const USER_VEHICLES_REMOVE = "USER_VEHICLES_REMOVE";
export const USER_VEHICLES_ARCHIVE_TOGGLE = "USER_VEHICLES_ARCHIVE_TOGGLE";
export const VEHICLE_ARCHIVE_TOGGLE = "VEHICLE_ARCHIVE_TOGGLE";
//MOBILE variables
export const MOBILE_ADDED = "MOBILE_ADDED";
export const CLEAR_MOBILE_MESSAGE = "CLEAR_MOBILE_MESSAGE";
export const GET_ALL_MOBILES_SUCCESS = "GET_ALL_MOBILES_SUCCESS";
export const DELETE_MOBILE_SUCCESS = "DELETE_MOBILE_SUCCESS";
export const DELETE_MOBILE_FAILED = "DELETE_MOBILE_FAILED";
export const MOBILE_EDIT_SUCCESS = "MOBILE_EDIT_SUCCESS";
export const MOBILE_EDIT_FAILED = "MOBILE_EDIT_FAILED";
export const USER_MOBILES_REMOVE = "USER_MOBILES_REMOVE";
export const USER_MOBILES_ARCHIVE_TOGGLE = "USER_MOBILES_ARCHIVE_TOGGLE";
export const MOBILE_ARCHIVE_TOGGLE = "MOBILE_ARCHIVE_TOGGLE";

//COMPUTER variables
export const COMPUTER_ADDED = "COMPUTER_ADDED";
export const CLEAR_COMPUTER_MESSAGE = "CLEAR_COMPUTER_MESSAGE";
export const GET_ALL_COMPUTERS_SUCCESS = "GET_ALL_COMPUTERS_SUCCESS";
export const DELETE_COMPUTER_SUCCESS = "DELETE_COMPUTER_SUCCESS";
export const DELETE_COMPUTER_FAILED = "DELETE_COMPUTER_FAILED";
export const COMPUTER_EDIT_SUCCESS = "COMPUTER_EDIT_SUCCESS";
export const COMPUTER_EDIT_FAILED = "COMPUTER_EDIT_FAILED";
export const USER_COMPUTERS_REMOVE = "USER_COMPUTERS_REMOVE";
export const USER_COMPUTERS_ARCHIVE_TOGGLE = "USER_COMPUTERS_ARCHIVE_TOGGLE";
export const COMPUTER_ARCHIVE_TOGGLE = "COMPUTER_ARCHIVE_TOGGLE";

//PRODUCT's INDIVIDUAL PAGE variables
export const SET_PRODUCT_LOADING = "SET_PRODUCT_LOADING";
export const GET_SELECTED_PRODUCT_SUCCESS = "GET_SELECTED_PRODUCT_SUCCESS";
export const GET_SELECTED_PRODUCT_FAILED = "GET_SELECTED_PRODUCT_FAILED";
//WISHLIST variables
export const GET_WISHES_SUCCESS = "GET_WISHES_SUCCESS";
export const WISH_ADDED = "WISH_ADDED";
export const SET_WISH_LOADING = "SET_WISH_LOADING";
export const CLEAR_WISHES = "CLEAR_WISHES";
export const ONE_WISH_DELETED = "ONE_WISH_DELETED";
